import { z } from 'zod';
import { PublicId } from './common.ts';
import { HouseDetailSchema } from './house-detail.ts';
import {
  HouseMonthQuerySchema,
  HouseMonthResponseSchema,
  HouseSearchQuerySchema,
  HouseSearchResponseSchema,
  HouseSummarySchema,
} from './houses.ts';
import {
  ActInfoSchema,
  ActReadyRequestSchema,
  AdsRegistrationRequestSchema,
  CreateIncidentRequestSchema,
  IncidentDetailSchema,
  IncidentIdParams,
  JoinRequestSchema,
  JoinResponseSchema,
  ObservationRequestSchema,
  ParticipationPatchSchema,
  ParticipationResponseSchema,
  RecalculationRequestSchema,
  RecalculationResponseSchema,
  ResultSchema,
  SendToDmRequestSchema,
  SendToDmResponseSchema,
} from './incidents.ts';
import {
  AuthDevRequestSchema,
  AuthMaxRequestSchema,
  ConsentRequestSchema,
  DemoUkRoleRequestSchema,
  MeSchema,
  ResidencyRequestSchema,
  ResidencyResponseSchema,
  SessionResponseSchema,
  SettingsPatchSchema,
  SettingsResponseSchema,
} from './me.ts';
import { NormsQuerySchema, NormsResponseSchema } from './norms.ts';
import {
  OwnerInviteCreateRequestSchema,
  OwnerInviteCreateResponseSchema,
  OwnerInviteDecisionResponseSchema,
  OwnerInviteViewSchema,
} from './owner.ts';
import { defineRoutes } from './route.ts';
import { HealthResponse, ReadyResponse, VersionResponse } from './system.ts';
import {
  ChatBindingInfoSchema,
  ChatBindingRequestSchema,
  ChatBindingResponseSchema,
  DemoNeighboursResponseSchema,
  DemoResetResponseSchema,
  HeatingPollResponseSchema,
  HeatMapSchema,
  HouseIdParams,
  IdempotencyHeaders,
  IfMatchHeaders,
  ResidentDecisionResponseSchema,
  ResidentsQuerySchema,
  ResidentsResponseSchema,
  TokenParams,
  UkHouseDetailSchema,
  UkHousesResponseSchema,
  UkIncidentDetailSchema,
  UkIncidentsQuerySchema,
  UkIncidentsResponseSchema,
  UkMergeRequestSchema,
  UkStatusRequestSchema,
} from './uk.ts';
import { MaxUpdateSchema, WebhookAckSchema, WebhookHeaders } from './webhook.ts';

const HouseIdPathParams = z.object({ houseId: PublicId });

export const systemRoutes = defineRoutes([
  {
    operationId: 'health',
    method: 'get',
    path: '/health',
    summary: 'Процесс жив',
    tags: ['system'],
    auth: 'none',
    responses: { 200: { description: 'Процесс жив', schema: HealthResponse } },
  },
  {
    operationId: 'healthV1',
    method: 'get',
    path: '/api/v1/health',
    summary: 'Процесс жив (путь с базой /api/v1)',
    tags: ['system'],
    auth: 'none',
    responses: { 200: { description: 'Процесс жив', schema: HealthResponse } },
  },
  {
    operationId: 'ready',
    method: 'get',
    path: '/ready',
    summary: 'Готовность: БД, миграции, MAX',
    tags: ['system'],
    auth: 'none',
    responses: {
      200: { description: 'Все зависимости готовы', schema: ReadyResponse },
      503: { description: 'Какая-то зависимость не готова', schema: ReadyResponse, contentType: 'application/json' },
    },
  },
  {
    operationId: 'version',
    method: 'get',
    path: '/api/v1/version',
    summary: 'Версия сборки и включённые функции',
    tags: ['system'],
    auth: 'none',
    responses: { 200: { description: 'Версия', schema: VersionResponse } },
  },
]);

export const authRoutes = defineRoutes([
  {
    operationId: 'authMax',
    method: 'post',
    path: '/api/v1/auth/max',
    summary: 'Вход по initData MAX',
    description:
      'Подпись initData проверяется по алгоритму MAX (HMAC-SHA256 с ключом WebAppData), auth_date не старше часа. Ответ — сессия JWT на 12 часов.',
    tags: ['auth'],
    auth: 'none',
    body: AuthMaxRequestSchema,
    responses: { 200: { description: 'Сессия', schema: SessionResponseSchema } },
    errors: [400, 401, 429],
  },
  {
    operationId: 'authDev',
    method: 'post',
    path: '/api/v1/auth/dev',
    summary: 'Вход вне MAX для разработки',
    description: 'Только при DEV_AUTH=true (локально). На стенде отвечает 404 независимо от клиента.',
    tags: ['auth'],
    auth: 'none',
    body: AuthDevRequestSchema,
    responses: { 200: { description: 'Сессия', schema: SessionResponseSchema } },
    errors: [400, 404],
  },
]);

export const meRoutes = defineRoutes([
  {
    operationId: 'getMe',
    method: 'get',
    path: '/api/v1/me',
    summary: 'Пользователь, проживание, уровень доверия, роли',
    tags: ['me'],
    auth: 'user',
    responses: { 200: { description: 'Профиль', schema: MeSchema } },
    errors: [401],
  },
  {
    operationId: 'giveConsent',
    method: 'post',
    path: '/api/v1/me/consent',
    summary: 'Согласие на обработку ПДн',
    tags: ['me'],
    auth: 'user',
    body: ConsentRequestSchema,
    responses: { 204: { description: 'Согласие сохранено' } },
    errors: [400, 401, 422],
  },
  {
    operationId: 'putResidency',
    method: 'put',
    path: '/api/v1/me/residency',
    summary: 'Дом, квартира и роль в квартире',
    description:
      'Нужно согласие (403 consent_required). Одна учётная запись MAX — одна квартира в доме; смена квартиры сбрасывает уровень доверия до 0. Квартира вне диапазона → 422 flat_out_of_range.',
    tags: ['me'],
    auth: 'user',
    body: ResidencyRequestSchema,
    responses: { 200: { description: 'Проживание сохранено', schema: ResidencyResponseSchema } },
    errors: [400, 401, 403, 404, 422],
  },
  {
    operationId: 'deleteMe',
    method: 'delete',
    path: '/api/v1/me',
    summary: 'Удалить мои данные',
    description: 'Удаляется проживание; участие в авариях и события обезличиваются.',
    tags: ['me'],
    auth: 'user',
    responses: { 204: { description: 'Данные удалены' } },
    errors: [401, 403],
  },
  {
    operationId: 'demoUkRole',
    method: 'post',
    path: '/api/v1/me/demo-uk-role',
    summary: 'Демо-код роли УК',
    description: 'Только при DEMO_MODE=true: выдаёт роль сотрудника «УК Модельная» с пометкой «Демо-роль».',
    tags: ['me', 'demo'],
    auth: 'user',
    body: DemoUkRoleRequestSchema,
    responses: { 200: { description: 'Роль выдана', schema: MeSchema } },
    errors: [400, 401, 403],
  },
  {
    operationId: 'patchSettings',
    method: 'patch',
    path: '/api/v1/me/settings',
    summary: 'Уведомления по умолчанию',
    tags: ['me'],
    auth: 'user',
    body: SettingsPatchSchema,
    responses: { 200: { description: 'Настройки', schema: SettingsResponseSchema } },
    errors: [400, 401],
  },
]);

export const houseRoutes = defineRoutes([
  {
    operationId: 'searchHouses',
    method: 'get',
    path: '/api/v1/houses/search',
    summary: 'Поиск модельных домов',
    tags: ['houses'],
    auth: 'user',
    query: HouseSearchQuerySchema,
    responses: { 200: { description: 'Дома', schema: HouseSearchResponseSchema } },
    errors: [401],
  },
  {
    operationId: 'getHouseSummary',
    method: 'get',
    path: '/api/v1/houses/{houseId}/summary',
    summary: 'Краткие сведения о доме для регистрации',
    description: 'Доступно любому вошедшему пользователю: адрес, подъезды, диапазон квартир (S02 по payload n_ или h_).',
    tags: ['houses'],
    auth: 'user',
    params: HouseIdPathParams,
    responses: { 200: { description: 'Дом', schema: HouseSummarySchema } },
    errors: [401, 404],
  },
  {
    operationId: 'getHouse',
    method: 'get',
    path: '/api/v1/houses/{houseId}',
    summary: 'Дом: активные аварии, итоги, месяц против лимита',
    tags: ['houses'],
    auth: 'user',
    params: HouseIdPathParams,
    responses: { 200: { description: 'Дом', schema: HouseDetailSchema } },
    errors: [401, 403, 404],
  },
  {
    operationId: 'getHouseMonth',
    method: 'get',
    path: '/api/v1/houses/{houseId}/month',
    summary: 'Перерывы услуги за месяц против лимита',
    description: 'Для жителя — по его квартире, для УК — по авариям масштаба «дом».',
    tags: ['houses'],
    auth: 'user',
    params: HouseIdPathParams,
    query: HouseMonthQuerySchema,
    responses: { 200: { description: 'Месяц', schema: HouseMonthResponseSchema } },
    errors: [400, 401, 403, 404],
  },
  {
    operationId: 'listNorms',
    method: 'get',
    path: '/api/v1/norms',
    summary: 'Справочник нормативов с основаниями',
    tags: ['norms'],
    auth: 'user',
    query: NormsQuerySchema,
    responses: { 200: { description: 'Нормы', schema: NormsResponseSchema } },
    errors: [400, 401],
  },
]);

export const incidentRoutes = defineRoutes([
  {
    operationId: 'createIncident',
    method: 'post',
    path: '/api/v1/incidents',
    summary: 'Сообщить об аварии',
    description: [
      'Авария создаётся после шага «где». Если в доме уже открыта авария того же вида не уровня «квартира» — 409 `duplicate_incident` с `duplicateOf`: клиент предлагает присоединиться (при гонке — присоединяет автоматически).',
      'Время в будущем → 422 `started_at_in_future`; старше 24 часов без `confirmOld` → 422 `confirm_old_required`.',
      'Житель уже сообщил о нескольких авариях за последний час → 429 `rate_limited` (защита от засорения; дом-песочница не ограничен, присоединение к открытой аварии — всегда).',
    ].join('\n\n'),
    tags: ['incidents'],
    auth: 'resident',
    headers: IdempotencyHeaders,
    body: CreateIncidentRequestSchema,
    responses: { 201: { description: 'Авария создана', schema: IncidentDetailSchema } },
    errors: [400, 401, 403, 404, 409, 422, 429],
  },
  {
    operationId: 'getIncident',
    method: 'get',
    path: '/api/v1/incidents/{id}',
    summary: 'Авария: сроки, счётчики, хронология',
    tags: ['incidents'],
    auth: 'user',
    params: IncidentIdParams,
    responses: { 200: { description: 'Авария', schema: IncidentDetailSchema } },
    errors: [401, 403, 404],
  },
  {
    operationId: 'joinIncident',
    method: 'post',
    path: '/api/v1/incidents/{id}/join',
    summary: '«У меня тоже» (+ подъезд, этаж)',
    description: 'Повторное нажатие — `joinResult: already_joined`, счётчики не меняются. Закрытая или объединённая авария → 409.',
    tags: ['incidents'],
    auth: 'resident',
    params: IncidentIdParams,
    body: JoinRequestSchema,
    responses: { 200: { description: 'Отметка сохранена', schema: JoinResponseSchema } },
    errors: [400, 401, 403, 404, 409, 422],
  },
  {
    operationId: 'leaveIncident',
    method: 'post',
    path: '/api/v1/incidents/{id}/leave',
    summary: '«Не у меня»',
    tags: ['incidents'],
    auth: 'resident',
    params: IncidentIdParams,
    responses: { 200: { description: 'Отметка сохранена', schema: IncidentDetailSchema } },
    errors: [401, 403, 404, 409],
  },
  {
    operationId: 'registerAds',
    method: 'post',
    path: '/api/v1/incidents/{id}/ads-registration',
    summary: 'Номер и время заявки АДС или «не дозвонился»',
    description:
      'Только участник аварии (нажал «У меня тоже» или сообщил о ней), иначе 403 `not_participant`. Время — не раньше начала аварии и не в будущем; номер, похожий на телефон, — 422 `ads_number_invalid`.',
    tags: ['incidents'],
    auth: 'resident',
    params: IncidentIdParams,
    body: AdsRegistrationRequestSchema,
    responses: { 200: { description: 'Сохранено', schema: IncidentDetailSchema } },
    errors: [400, 401, 403, 404, 409, 422],
  },
  {
    operationId: 'postObservation',
    method: 'post',
    path: '/api/v1/incidents/{id}/observations',
    summary: 'Бригада видна / нет; услуга есть / нет / плохая',
    tags: ['incidents'],
    auth: 'resident',
    params: IncidentIdParams,
    body: ObservationRequestSchema,
    responses: { 200: { description: 'Отметка сохранена', schema: IncidentDetailSchema } },
    errors: [400, 401, 403, 404, 409],
  },
  {
    operationId: 'patchParticipation',
    method: 'patch',
    path: '/api/v1/incidents/{id}/participation',
    summary: '«Уведомлять меня»',
    tags: ['incidents'],
    auth: 'resident',
    params: IncidentIdParams,
    body: ParticipationPatchSchema,
    responses: { 200: { description: 'Сохранено', schema: ParticipationResponseSchema } },
    errors: [400, 401, 404],
  },
  {
    operationId: 'getIncidentResult',
    method: 'get',
    path: '/api/v1/incidents/{id}/result',
    summary: 'Итог аварии',
    tags: ['incidents'],
    auth: 'user',
    params: IncidentIdParams,
    responses: { 200: { description: 'Итог', schema: ResultSchema } },
    errors: [401, 403, 404, 409],
  },
  {
    operationId: 'recalculate',
    method: 'post',
    path: '/api/v1/incidents/{id}/recalculation',
    summary: 'Расчёт перерасчёта по нормам',
    description: [
      'Считается по квартире пользователя: превышение месячного лимита = объединение перерывов услуги за месяц − допустимые часы; округление — по справочнику.',
      'Доступно для закрытых аварий и для checking/discrepancy (`preliminary: true`). Превышения нет → 200 с `amount: 0`. Сумма ≤ 0 или не число → 422 `monthly_charge_invalid`.',
      'Поля `excessHours`, `ratePercent`, `amount`, `disclaimer` присутствуют всегда. Ничего не сохраняется.',
    ].join('\n\n'),
    tags: ['incidents'],
    auth: 'resident',
    params: IncidentIdParams,
    headers: IdempotencyHeaders,
    body: RecalculationRequestSchema,
    responses: { 200: { description: 'Расчёт', schema: RecalculationResponseSchema } },
    errors: [400, 401, 403, 404, 409, 422],
  },
  {
    operationId: 'sendApplicationToDm',
    method: 'post',
    path: '/api/v1/incidents/{id}/application/send-to-dm',
    summary: 'Бот присылает заявление в личку',
    description:
      'Синхронный вызов MAX (тайм-аут 10 с, одна повторная попытка). Текст не сохраняется и не логируется. Диалог с ботом не начат → 409 `dialog_not_started` с `botLink`; MAX недоступен → 502.',
    tags: ['incidents'],
    auth: 'resident',
    params: IncidentIdParams,
    body: SendToDmRequestSchema,
    responses: { 200: { description: 'Отправлено', schema: SendToDmResponseSchema } },
    errors: [400, 401, 403, 404, 409, 422, 502],
  },
  {
    operationId: 'actReady',
    method: 'post',
    path: '/api/v1/incidents/{id}/act/ready',
    summary: '«Я готов подписать» акт без исполнителя',
    description:
      'Когда согласившихся на знакомство двое и больше, бот присылает каждому в личку упоминания профилей MAX друг друга; контакты не хранятся.',
    tags: ['incidents'],
    auth: 'resident',
    params: IncidentIdParams,
    body: ActReadyRequestSchema,
    responses: { 200: { description: 'Сохранено', schema: ActInfoSchema } },
    errors: [400, 401, 403, 404, 409],
    feature: 'actTemplate',
  },
]);

export const ownerRoutes = defineRoutes([
  {
    operationId: 'createOwnerInvite',
    method: 'post',
    path: '/api/v1/owner-invites',
    summary: 'Ссылка для собственника',
    tags: ['owner'],
    auth: 'resident',
    body: OwnerInviteCreateRequestSchema,
    responses: { 201: { description: 'Ссылка', schema: OwnerInviteCreateResponseSchema } },
    errors: [400, 401, 403, 404],
    feature: 'trustLevels',
  },
  {
    operationId: 'getOwnerInvite',
    method: 'get',
    path: '/api/v1/owner-invites/{token}',
    summary: 'Запрос на подтверждение жильца (S10)',
    tags: ['owner'],
    auth: 'user',
    params: TokenParams,
    responses: { 200: { description: 'Запрос', schema: OwnerInviteViewSchema } },
    errors: [401, 404, 410],
    feature: 'trustLevels',
  },
  {
    operationId: 'confirmOwnerInvite',
    method: 'post',
    path: '/api/v1/owner-invites/{token}/confirm',
    summary: 'Подтвердить жильца',
    tags: ['owner'],
    auth: 'user',
    params: TokenParams,
    responses: { 200: { description: 'Жилец подтверждён (уровень 2)', schema: OwnerInviteDecisionResponseSchema } },
    errors: [401, 404, 410],
    feature: 'trustLevels',
  },
  {
    operationId: 'rejectOwnerInvite',
    method: 'post',
    path: '/api/v1/owner-invites/{token}/reject',
    summary: '«Не знаю этого человека»',
    description: 'Уровень доверия жильца не меняется.',
    tags: ['owner'],
    auth: 'user',
    params: TokenParams,
    responses: { 200: { description: 'Отмечено', schema: OwnerInviteDecisionResponseSchema } },
    errors: [401, 404, 410],
    feature: 'trustLevels',
  },
]);

export const ukRoutes = defineRoutes([
  {
    operationId: 'ukListIncidents',
    method: 'get',
    path: '/api/v1/uk/incidents',
    summary: 'Аварии всех домов УК',
    tags: ['uk'],
    auth: 'staff',
    query: UkIncidentsQuerySchema,
    responses: { 200: { description: 'Аварии', schema: UkIncidentsResponseSchema } },
    errors: [400, 401, 403],
  },
  {
    operationId: 'ukGetIncident',
    method: 'get',
    path: '/api/v1/uk/incidents/{id}',
    summary: 'Авария для УК: сетка «подъезд × этаж», жители, действия',
    tags: ['uk'],
    auth: 'staff',
    params: IncidentIdParams,
    responses: { 200: { description: 'Авария', schema: UkIncidentDetailSchema } },
    errors: [401, 403, 404],
  },
  {
    operationId: 'ukSetStatus',
    method: 'post',
    path: '/api/v1/uk/incidents/{id}/status',
    summary: 'Статус и ориентир УК',
    description: [
      'Каждая смена статуса: событие в хронологии, правка карточки в чате (асинхронно), уведомления присоединившимся. Пропуск шагов разрешён и виден в хронологии.',
      'Недопустимый переход → 409 `invalid_transition`; устаревший If-Match → 409 `version_conflict` с `currentVersion`. Для accepted без eta → 422 `eta_required`.',
    ].join('\n\n'),
    tags: ['uk'],
    auth: 'staff',
    params: IncidentIdParams,
    headers: IfMatchHeaders,
    body: UkStatusRequestSchema,
    responses: { 200: { description: 'Статус сохранён', schema: UkIncidentDetailSchema } },
    errors: [400, 401, 403, 404, 409, 422],
  },
  {
    operationId: 'ukMerge',
    method: 'post',
    path: '/api/v1/uk/incidents/{id}/merge',
    summary: 'Объединить дубль с другой аварией',
    tags: ['uk'],
    auth: 'staff',
    params: IncidentIdParams,
    headers: IfMatchHeaders,
    body: UkMergeRequestSchema,
    responses: { 200: { description: 'Актуальная авария после объединения', schema: UkIncidentDetailSchema } },
    errors: [400, 401, 403, 404, 409],
  },
  {
    operationId: 'ukListHouses',
    method: 'get',
    path: '/api/v1/uk/houses',
    summary: 'Дома УК, чаты, права бота',
    tags: ['uk'],
    auth: 'staff',
    responses: { 200: { description: 'Дома', schema: UkHousesResponseSchema } },
    errors: [401, 403],
  },
  {
    operationId: 'ukGetHouse',
    method: 'get',
    path: '/api/v1/uk/houses/{id}',
    summary: 'Дом: параметры, чат, права бота, итог месяца',
    tags: ['uk'],
    auth: 'staff',
    params: HouseIdParams,
    responses: { 200: { description: 'Дом', schema: UkHouseDetailSchema } },
    errors: [401, 403, 404],
  },
  {
    operationId: 'ukGetChatBinding',
    method: 'get',
    path: '/api/v1/uk/chat-bindings/{token}',
    summary: 'Чат для привязки по токену из payload c_',
    tags: ['uk'],
    auth: 'staff',
    params: TokenParams,
    responses: { 200: { description: 'Чат', schema: ChatBindingInfoSchema } },
    errors: [401, 403, 404, 410],
  },
  {
    operationId: 'ukBindChat',
    method: 'post',
    path: '/api/v1/uk/chat-bindings',
    summary: 'Привязать чат к дому',
    description: 'Публикует и закрепляет панель дома (C01). Если бот не администратор — панель без закрепа.',
    tags: ['uk'],
    auth: 'staff',
    body: ChatBindingRequestSchema,
    responses: { 200: { description: 'Чат привязан', schema: ChatBindingResponseSchema } },
    errors: [400, 401, 403, 404, 409, 410],
  },
  {
    operationId: 'ukHeatmap',
    method: 'get',
    path: '/api/v1/uk/houses/{id}/heatmap',
    summary: 'Тепловая карта по опросу «Тепло ли у вас?»',
    tags: ['uk'],
    auth: 'staff',
    params: HouseIdParams,
    responses: { 200: { description: 'Тепловая карта', schema: HeatMapSchema } },
    errors: [401, 403, 404],
    feature: 'polls',
  },
  {
    operationId: 'ukStartHeatingPoll',
    method: 'post',
    path: '/api/v1/uk/houses/{id}/polls/heating',
    summary: 'Запустить «Тепло ли у вас?» (раз за сезон)',
    tags: ['uk'],
    auth: 'staff',
    params: HouseIdParams,
    responses: { 202: { description: 'Опрос поставлен в очередь', schema: HeatingPollResponseSchema } },
    errors: [401, 403, 404, 409],
    feature: 'polls',
  },
  {
    operationId: 'ukListResidents',
    method: 'get',
    path: '/api/v1/uk/residents',
    summary: 'Очередь подтверждения жильцов',
    tags: ['uk'],
    auth: 'staff',
    query: ResidentsQuerySchema,
    responses: { 200: { description: 'Заявки', schema: ResidentsResponseSchema } },
    errors: [400, 401, 403],
    feature: 'trustLevels',
  },
  {
    operationId: 'ukConfirmResident',
    method: 'post',
    path: '/api/v1/uk/residents/{id}/confirm',
    summary: 'Подтвердить жильца (уровень 2)',
    tags: ['uk'],
    auth: 'staff',
    params: HouseIdParams,
    responses: { 200: { description: 'Подтверждён', schema: ResidentDecisionResponseSchema } },
    errors: [401, 403, 404],
    feature: 'trustLevels',
  },
  {
    operationId: 'ukRejectResident',
    method: 'post',
    path: '/api/v1/uk/residents/{id}/reject',
    summary: 'Отклонить заявку (уровень остаётся 0)',
    tags: ['uk'],
    auth: 'staff',
    params: HouseIdParams,
    responses: { 200: { description: 'Отклонена', schema: ResidentDecisionResponseSchema } },
    errors: [401, 403, 404],
    feature: 'trustLevels',
  },
  {
    operationId: 'demoNeighbours',
    method: 'post',
    path: '/api/v1/uk/houses/{id}/demo/neighbours',
    summary: 'Добавить 5 модельных соседей в активную аварию',
    description: 'Уровень доверия 1, разные подъезды; через DEMO_NEIGHBOUR_ANSWER_DELAY_SEC после вопроса о восстановлении сами отвечают «Да».',
    tags: ['demo'],
    auth: 'demo_staff',
    params: HouseIdParams,
    responses: { 200: { description: 'Соседи добавлены', schema: DemoNeighboursResponseSchema } },
    errors: [401, 403, 404, 409],
  },
  {
    operationId: 'demoTimeShift',
    method: 'post',
    path: '/api/v1/uk/incidents/{id}/demo/time-shift',
    summary: 'Сдвинуть начало аварии на 6 ч назад',
    description: 'Только модельные дома; пересчитывает сроки и итог, событие demo_time_shift в хронологии.',
    tags: ['demo'],
    auth: 'demo_staff',
    params: IncidentIdParams,
    responses: { 200: { description: 'Сдвинуто', schema: UkIncidentDetailSchema } },
    errors: [401, 403, 404, 409],
  },
  {
    operationId: 'demoReset',
    method: 'post',
    path: '/api/v1/uk/houses/{id}/demo/reset',
    summary: 'Сбросить демо-данные дома',
    tags: ['demo'],
    auth: 'demo_staff',
    params: HouseIdParams,
    responses: { 200: { description: 'Сброшено', schema: DemoResetResponseSchema } },
    errors: [401, 403, 404],
  },
  {
    operationId: 'sandboxReset',
    method: 'post',
    path: '/api/v1/sandbox/reset',
    summary: 'Очистить аварии дома-песочницы',
    description: 'Только checker-УК при CHECKER_API_ENABLED=true. Сообщений в чаты нет.',
    tags: ['sandbox'],
    auth: 'checker_uk',
    responses: { 204: { description: 'Песочница очищена' } },
    errors: [401, 403, 404],
  },
]);

export const webhookRoutes = defineRoutes([
  {
    operationId: 'maxWebhook',
    method: 'post',
    path: '/webhook/max',
    summary: 'События бота MAX (внутренний)',
    description:
      'Секрет сравнивается за постоянное время; событие дедуплицируется и ставится в очередь, ответ — сразу. БД недоступна → 503, MAX повторит доставку.',
    tags: ['webhook'],
    auth: 'webhook',
    headers: WebhookHeaders,
    body: MaxUpdateSchema,
    responses: { 200: { description: 'Принято', schema: WebhookAckSchema } },
    errors: [400, 401, 503],
  },
]);

export const apiRoutes = [
  ...systemRoutes,
  ...authRoutes,
  ...meRoutes,
  ...houseRoutes,
  ...incidentRoutes,
  ...ownerRoutes,
  ...ukRoutes,
  ...webhookRoutes,
];
