// Типы ответов и запросов API для мини-приложения: z.infer по схемам контракта.
// Собирается вручную из схем этого пакета; при новой схеме — добавьте тип сюда.
import type { z } from 'zod';
import type { AppRoleSchema } from './enums.ts';
import type { HouseChatInfoSchema, HouseMonthQuerySchema, HouseMonthResponseSchema, HouseMonthSummarySchema, HouseSearchQuerySchema, HouseSearchResponseSchema, MonthServiceSchema } from './houses.ts';
import type { ActInfoSchema, ActReadyRequestSchema, AdsInfoSchema, AdsRegistrationRequestSchema, CheckInfoSchema, CountersSchema, EntranceCountSchema, HeadlineSchema, IncidentHouseRefSchema, JoinRequestSchema, JoinResponseSchema, MyParticipationSchema, ObservationRequestSchema, ParticipationPatchSchema, ParticipationResponseSchema, RecalculationRequestSchema, RecalculationResponseSchema, ResultSchema, SendToDmRequestSchema, SendToDmResponseSchema, StatusStepSchema, TimelineEventSchema } from './incidents.ts';
import type { AuthDevRequestSchema, AuthMaxRequestSchema, ConsentRequestSchema, DemoUkRoleRequestSchema, ResidencySchema, ResidencyRequestSchema, ResidencyResponseSchema, SessionResponseSchema, SettingsPatchSchema, SettingsResponseSchema, StaffInfoSchema } from './me.ts';
import type { NormsQuerySchema, NormsResponseSchema } from './norms.ts';
import type { OwnerInviteCreateRequestSchema, OwnerInviteCreateResponseSchema, OwnerInviteDecisionResponseSchema, OwnerInviteViewSchema } from './owner.ts';
import type { ChatBindingInfoSchema, ChatBindingRequestSchema, ChatBindingResponseSchema, DemoNeighboursResponseSchema, DemoResetResponseSchema, EntranceFloorGridSchema, HeatMapSchema, HeatingPollResponseSchema, MonthlySummarySchema, ResidentDecisionResponseSchema, ResidentRequestSchema, ResidentsQuerySchema, ResidentsResponseSchema, UkActionSchema, UkHouseSchema, UkHouseDetailSchema, UkHousesResponseSchema, UkIncidentDetailSchema, UkIncidentsQuerySchema, UkIncidentsResponseSchema, UkMergeRequestSchema, UkStatusRequestSchema } from './uk.ts';

export type AppRole = z.infer<typeof AppRoleSchema>;
export type HouseChatInfo = z.infer<typeof HouseChatInfoSchema>;
export type HouseMonthQuery = z.infer<typeof HouseMonthQuerySchema>;
export type HouseMonthResponse = z.infer<typeof HouseMonthResponseSchema>;
export type HouseMonthSummary = z.infer<typeof HouseMonthSummarySchema>;
export type HouseSearchQuery = z.infer<typeof HouseSearchQuerySchema>;
export type HouseSearchResponse = z.infer<typeof HouseSearchResponseSchema>;
export type MonthService = z.infer<typeof MonthServiceSchema>;
export type ActInfo = z.infer<typeof ActInfoSchema>;
export type ActReadyRequest = z.infer<typeof ActReadyRequestSchema>;
export type AdsInfo = z.infer<typeof AdsInfoSchema>;
export type AdsRegistrationRequest = z.infer<typeof AdsRegistrationRequestSchema>;
export type CheckInfo = z.infer<typeof CheckInfoSchema>;
export type Counters = z.infer<typeof CountersSchema>;
export type EntranceCount = z.infer<typeof EntranceCountSchema>;
export type Headline = z.infer<typeof HeadlineSchema>;
export type IncidentHouseRef = z.infer<typeof IncidentHouseRefSchema>;
export type JoinRequest = z.infer<typeof JoinRequestSchema>;
export type JoinResponse = z.infer<typeof JoinResponseSchema>;
export type MyParticipation = z.infer<typeof MyParticipationSchema>;
export type ObservationRequest = z.infer<typeof ObservationRequestSchema>;
export type ParticipationPatch = z.infer<typeof ParticipationPatchSchema>;
export type ParticipationResponse = z.infer<typeof ParticipationResponseSchema>;
export type RecalculationRequest = z.infer<typeof RecalculationRequestSchema>;
export type RecalculationResponse = z.infer<typeof RecalculationResponseSchema>;
export type Result = z.infer<typeof ResultSchema>;
export type SendToDmRequest = z.infer<typeof SendToDmRequestSchema>;
export type SendToDmResponse = z.infer<typeof SendToDmResponseSchema>;
export type StatusStep = z.infer<typeof StatusStepSchema>;
export type TimelineEvent = z.infer<typeof TimelineEventSchema>;
export type AuthDevRequest = z.infer<typeof AuthDevRequestSchema>;
export type AuthMaxRequest = z.infer<typeof AuthMaxRequestSchema>;
export type ConsentRequest = z.infer<typeof ConsentRequestSchema>;
export type DemoUkRoleRequest = z.infer<typeof DemoUkRoleRequestSchema>;
export type Residency = z.infer<typeof ResidencySchema>;
export type ResidencyRequest = z.infer<typeof ResidencyRequestSchema>;
export type ResidencyResponse = z.infer<typeof ResidencyResponseSchema>;
export type SessionResponse = z.infer<typeof SessionResponseSchema>;
export type SettingsPatch = z.infer<typeof SettingsPatchSchema>;
export type SettingsResponse = z.infer<typeof SettingsResponseSchema>;
export type StaffInfo = z.infer<typeof StaffInfoSchema>;
export type NormsQuery = z.infer<typeof NormsQuerySchema>;
export type NormsResponse = z.infer<typeof NormsResponseSchema>;
export type OwnerInviteCreateRequest = z.infer<typeof OwnerInviteCreateRequestSchema>;
export type OwnerInviteCreateResponse = z.infer<typeof OwnerInviteCreateResponseSchema>;
export type OwnerInviteDecisionResponse = z.infer<typeof OwnerInviteDecisionResponseSchema>;
export type OwnerInviteView = z.infer<typeof OwnerInviteViewSchema>;
export type ChatBindingInfo = z.infer<typeof ChatBindingInfoSchema>;
export type ChatBindingRequest = z.infer<typeof ChatBindingRequestSchema>;
export type ChatBindingResponse = z.infer<typeof ChatBindingResponseSchema>;
export type DemoNeighboursResponse = z.infer<typeof DemoNeighboursResponseSchema>;
export type DemoResetResponse = z.infer<typeof DemoResetResponseSchema>;
export type EntranceFloorGrid = z.infer<typeof EntranceFloorGridSchema>;
export type HeatMap = z.infer<typeof HeatMapSchema>;
export type HeatingPollResponse = z.infer<typeof HeatingPollResponseSchema>;
export type MonthlySummary = z.infer<typeof MonthlySummarySchema>;
export type ResidentDecisionResponse = z.infer<typeof ResidentDecisionResponseSchema>;
export type ResidentRequest = z.infer<typeof ResidentRequestSchema>;
export type ResidentsQuery = z.infer<typeof ResidentsQuerySchema>;
export type ResidentsResponse = z.infer<typeof ResidentsResponseSchema>;
export type UkAction = z.infer<typeof UkActionSchema>;
export type UkHouse = z.infer<typeof UkHouseSchema>;
export type UkHouseDetail = z.infer<typeof UkHouseDetailSchema>;
export type UkHousesResponse = z.infer<typeof UkHousesResponseSchema>;
export type UkIncidentDetail = z.infer<typeof UkIncidentDetailSchema>;
export type UkIncidentsQuery = z.infer<typeof UkIncidentsQuerySchema>;
export type UkIncidentsResponse = z.infer<typeof UkIncidentsResponseSchema>;
export type UkMergeRequest = z.infer<typeof UkMergeRequestSchema>;
export type UkStatusRequest = z.infer<typeof UkStatusRequestSchema>;
